# -*- coding: utf-8 -*-
"""Basic Introduction to Image Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UcIVXZvTDhvEQG2QGU152oNg0VahDvu

# **Installing OpenCV From Prebuilt Binaries**
"""

pip install opencv-python

import cv2

pip install opencv-python

pip install numpy

pip install matplotlib

"""# **Reading Image as Color Image in OpenCV-Python**"""

from google.colab.patches import cv2_imshow

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2ff18
import cv2
img = cv2.imread('Robo.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

"""# **Reading Image as Color or GrayScale Image in OpenCV-Python**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2ff
import cv2
img = cv2.imread('Robo.jpg', cv2.IMREAD_GRAYSCALE)
cv2_imshow(img)

"""# **Read Image from Height 100–200 Pixel and Width 200–400 Pixel**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2ff
import cv2
img = cv2.imread('Robo.jpg',1)
roi = img[100 : 200, 200 : 400]
cv2_imshow(roi)

"""# **Resize image to 200px 180px ( Width Height )**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2
import cv2
img = cv2.imread('Robo.jpg',1)
resize = cv2.resize(img, (200, 180))
cv2_imshow(resize)

"""# **Rotating the Image**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2
import cv2
img = cv2.imread('Robo.jpg',1)
h,w = img.shape[:2]
center = (w // 2, h // 2) 
matrix = cv2.getRotationMatrix2D(center, 45, 0.5)  
rotated = cv2.warpAffine(img, matrix, (w, h)) 
cv2_imshow(rotated)

"""# **Drawing a Rectangle on image**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2
import cv2
img = cv2.imread('Robo.jpg',1)
output = img.copy() 
rectangle = cv2.rectangle(output, (400, 400),(800, 200), (0, 255, 0), 5) 

cv2_imshow(rectangle)

"""# **Displaying text on Image in Python using OpenCV**"""

!curl -o Robo.jpg blob:https://colab.research.google.com/47b259a1-5215-4c86-936f-750265b2
import cv2
img = cv2.imread('Robo.jpg',1)
output = img.copy() 
text = cv2.putText(output, 'www.Robo.org.in', (120, 25),  cv2.FONT_HERSHEY_SIMPLEX, 1, (60, 60, 60), 2)

cv2_imshow(text)